version: 2

project_name: snake

builds:
  - id: snake
    main: ./cmd
    binary: snake
    targets:
      - snake_Linux_amd64
      - snake_Linux_x86_64
      - snake_Darwin_amd64
      - snake_Darwin_x86_64
    ldflags:
      - "-s -w"

archives:
  - id: snake-archive
    formats: [tar.gz]
    files:
      - LICENSE
      - README.md

brews:
  - name: snake
    repository:
      owner: Mehulparekh144
      name: homebrew-tap
    commit_author:
      name: Mehul Parekh
      email: you@example.com
    description: "A terminal-based Snake game written in Go"
    homepage: "https://github.com/Mehulparekh144/go-snake"
    license: "MIT"
    install: |
      bin.install "snake"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: Mehulparekh144
    name: go-snake
  draft: false
